// <auto-generated />
using LinguaDesk.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinguaDesk.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LinguaDeskDbContext))]
    [Migration("20260908221711_InitialStorage")]
    partial class InitialStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");
#pragma warning restore 612, 618
        }
    }
}
